name: test
on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: go test -mod vendor ./... -race -coverprofile=coverage.txt -covermode=atomic
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          files: ./coverage.txt
      - uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: f67d5962d5ed7dfcecacdf7aed265a30164b6aa00590a599dc9ac0bdf116d3ae
        with:
          coverageCommand: go test -coverprofile c.out -v ./...
          prefix: github.com/martinhrvn/go-clean
